spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam_0591?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  ### 配置Redis
  redis:
    database: 0
    host: 10.0.0.32
    port: 6379
    password: 1470634109